server:
  port: 9005
spring:
  application:
    name: SN-gathering
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.149.128:3307/SN_gathering?characterEncoding=UTF8
    username: root
    password: ok
  jpa:
    database: MySQL
    show-sql: true